- name: Playbook
  hosts: VM
  
  become: yes
  tasks:
    - name: Copy file
      ansible.builtin.copy:
        src: hostfile.log
        dest: /home/jester

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present                
