- name: Playbook
  hosts: VM
  
  become: true
  tasks:
    - name: Copy file
      ansible.builtin.copy:
        src: hostfile.log
        dest: /home/jester
        
    - name: install dependencies  #Just the name of the task
      ansible.builtin.apt:        #Manages apt packages
        name:                     #A list of package names. aliases: package, pgk
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: latest             #ensures that the latest version is installed: default="present"
        update_cache: true
        check_mode: true
