- name: docker_playbook
  hosts: VM
  become: yes
  tasks:
    - name: install docker dependencies
      ansible.builtin.apt:
        name:                     #A list of package names. aliases: package, pgk
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: latest             #ensures that the latest version is installed: default="present"
        update_cache: true
        
    - name: install gpg key 
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg #| sudo gpg  
  #URL and command taken from the offical docker documentation -> Install Docker on Ubunut  
        keyring: /etc/apt/keyrings
        
    - name: add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
