Service yaml template:
apiVersion: v1
kind: Service
metadata:
  name: roman-service
  namespace: romanginx
spec:
  selector:
    app: romanginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081