---
- name: Install Jenkins on a Virtual Machine
  hosts: all
  become: true
  tasks:
  - name: Update package list
    apt: update_cache=yes
  - name: Install Java
    apt: name=default-jdk state=present
  - name: Add an Apt singing key
    ansible.builtin.apt_key: 
      state: present
      url: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
  - name: Install Jenkins
    apt: name=jenkins state=present
  - name: Start Jenkins Service
    service: name=jenkins state=started
