deployment template:
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment
  namespace: romanginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: romanginx
  template:
    metadata:
      labels:
        app: romanginx
    spec:
      containers:
      - name: romanginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80